name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build project
      run: "mvn package"

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/revisionProgram.jar

      
      
