name: Release for Windows
permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build project
      run: "mvn package"

    - name: Package for windows
      run: .idea/windows.bat

    # Rename the artifact using the release tag
    - name: Rename build artifact based on release tag
      shell: bash
      run: mv "target/Revision Program-1.0.exe" "target/Revision Program-${{github.event.release.tag_name}}.exe"

    - name: Upload asset to release
      uses: softprops/action-gh-release@v1
      with:
        files: "target/Revision Program-${{github.event.release.tag_name}}.exe"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
